name: "Alkim Kaya"
username: "adotkaya"
bio: "Software Developer | Computer Engineer"
github: "https://github.com/adotkaya"
linkedin: "https://linkedin.com/in/adotkaya"
location: "Izmir, Türkiye"
about: "Just a chill guy who loves coding. Fully immersed in Go. I care about clean architecture, concurrency, and building systems that scale. Currently based in Izmir, always learning. Rest is just gaming, reading and Galatasaray. My computer decided to kill itself so i wont be able to code for a while :D"
